version: '3'

services:
  auth-api:
    build: ./auth-api
    ports:
      - "8000:8000"
    environment:
      - AUTH_API_PORT=8000
      - JWT_SECRET=PRFT
      - USERS_API_ADDRESS=http://users-api:8083
    depends_on:
      - users-api
    restart: on-failure
    networks:
      - microservices-net

  users-api:
    build: ./users-api
    ports:
      - "8083:8083"
    environment:
      - SERVER_PORT=8083
      - JWT_SECRET=PRFT
    restart: on-failure
    networks:
      - microservices-net

  todos-api:
    build: ./todos-api
    ports:
      - "8082:8082"
    environment:
      - TODO_API_PORT=8082
      - JWT_SECRET=PRFT
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
    depends_on:
      - redis
    restart: on-failure
    networks:
      - microservices-net

  log-message-processor:
    build: ./log-message-processor
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
    depends_on:
      - redis
    restart: on-failure
    networks:
      - microservices-net

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - AUTH_API_ADDRESS=http://auth-api:8000
      - TODOS_API_ADDRESS=http://todos-api:8082
    depends_on:
      - auth-api
      - todos-api
    restart: on-failure
    networks:
      - microservices-net

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    networks:
      - microservices-net
    volumes:
      - redis-data:/data

networks:
  microservices-net:
    driver: bridge

volumes:
  redis-data: